### PR TITLE
Zhexu/peft

### PR DESCRIPTION
**Pull request by zhenghax**
Add PEFT Stage to Launcher. 
Unify PEFT training methods including ptuning, lora, ia3 and adapter.
Edit Launcher's stage and main files to add PEFT stage.
Edit config yaml file to add PEFT stage, and create yaml file for GPT Squad.

The four PEFT training methods ptuning, lora, ia3 and adapter with databricks dolly dataset could complete without any error on BCP.

### CODE REVIEW

**Review by dimapihtar — COMMENTED** [review]
could you add related documentation to README, please? Thanks.

**Comment by zhenghax** [comment]
Will add PEFT related documentation to the README. Thanks!

**Comment by zhenghax** [comment]
Have updated the README about PEFT Training with NeMo Megatron Launcher. Please help review. Thanks!

**Review by dimapihtar — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
