### PR TITLE
Added a new dataprep workflow for the Slim Pajama Dataset. 

### PR DESCRIPTION
**Pull request by kashkMoney**
Covers downloading, extracting, and preprocessing. Could hopefully be used as a drop in replacement for the missing pile dataset

### CODE REVIEW

**Comment by kashkMoney** [comment]
@dimapihtar Can you please rerun the tests?

**Comment by dimapihtar** [comment]
@kashkMoney could you resolve the conflicts, please?

**Comment by kashkMoney** [comment]
@dimapihtar Conflict is fixed.

**Comment by kashkMoney** [comment]
@dimapihtar Can you please rerun the tests?

**Review by dimapihtar — APPROVED** [review]
LGTM. Thank you!

**Comment by kashkMoney** [comment]
@dimapihtar @terrykong  I added in the option for choosing the dataset sources. Can you please rerun the tests?

**Review by dimapihtar — APPROVED** [review]
LGTM. Thank you!

**Comment by bdubauski** [comment]
Is there an ETA for getting this PR completed?

**Pull request merged**
