### PR TITLE
Fix download & extract script for BCP

### PR DESCRIPTION
**Pull request by pihao7**
The fix is similar to what @roclark did in [commit 1418933](https://github.com/NVIDIA/NeMo-Megatron-Launcher/commit/1418933e750cd9b6fdbed65cb2982a6046012b08)

@ericharper @maanug-nv Can you review this?

### CODE REVIEW

**Comment by ericharper** [comment]
Could you fix the code style?

**Comment by pihao7** [comment]
> Could you fix the code style?

fixed.

**Comment by dimapihtar** [comment]
@ericharper could you review, please?

**Review by dimapihtar — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
