### PR TITLE
Add baichuan2 support

### PR DESCRIPTION
**Pull request by Euynaheh**
Add Chinese LLM Baichuan2 (7B/13B) launcher support, including auto_configurator, conversion, data_preparation, evaluation, fine_tuning, peft, training.

### CODE REVIEW

**Review by dimapihtar — CHANGES_REQUESTED** [review]
Could you please resolve the conflicts and fix the code style with black?

**Comment by dimapihtar** [comment]
@Euynaheh could fix the code style, please?
`cd NeMo-Megaton-Launcher
black . --check --verbose --diff`

**Comment by Euynaheh** [comment]
> @Euynaheh could fix the code style, please? `black . --check --verbose --diff` and fix the differencies

@dimapihtar This command fixed code style in the whole repo, which made some codes different from NVIDIA:master. Are you sure I should apply this command and commit?

**Comment by dimapihtar** [comment]
@Euynaheh 
it shows me only two files would be reformatted (that you've been modifying)ю
could you try it with black==19.10b0, please?

**Comment by Euynaheh** [comment]
> > @dimapihtar Thanks! With black==19.10b0 only two files need to be reformatted. I fixed one but remain one file (auto_configurator/autoconfig/utils.py) unchanged, because I saw the code style is the same as NVIDIA:master.
> 
> @Euynaheh could you run this command, please? `black launcher_scripts/nemo_launcher/core/stages.py` because anyway we need to get this test passed before merging.

**Comment by Euynaheh** [comment]
@dimapihtar I run this command and returned "All done!". It seems launcher_scripts/nemo_launcher/core/stages.py have the same code style with NVIDIA:master. Is it different at your side? I'm using black==19.10b0.

**Pull request merged**
