### PR TITLE
Add support for training GPT models on Kubernetes

### PR DESCRIPTION
**Pull request by roclark**
Adding kubernetes support for preparing datasets and training GPT-based foundation models with NeMo Framework. The kubernetes support creates a Helm chart based off the cluster config settings and each task is launched as a distributed job via Helm. Currently, kubernetes support assumes the following:
  * Recent versions of the GPU, Network, and Kubeflow Operators are installed.
  * InfiniBand adapters are labeled as node resources if running multi-node jobs.
  * The launcher is run from a controller node with access to `kubectl` and `helm` and can launch jobs on the cluster.
  * The controller node has the ability to install various Python dependencies, including Hydra.
  * All data including the launcher scripts and results/checkpoints will be stored on an NFS filer attached to all nodes.

A new k8s cluster setting and config file have been included to allow jobs to run on specific kubernetes cluster.

### CODE REVIEW

**Comment by ericharper** [comment]
@dimapihtar and @maanug-nv can you help to review?

**Review by maanug-nv — COMMENTED** [review]
Content looks good to me. 
Two questions. How would this README content fit into the User Guide that we are also working on, @ericharper ?
Also, can we run a CI pipeline on NeMo-CI with the container built using the top of this branch for the launcher, just to ensure existing functionality doesn't break? @dimapihtar could you do that?

**Comment by dimapihtar** [comment]
> Content looks good to me. Two questions. How would this README content fit into the User Guide that we are also working on, @ericharper ? Also, can we run a CI pipeline on NeMo-CI with the container built using the top of this branch for the launcher, just to ensure existing functionality doesn't break? @dimapihtar could you do that?

yes, that makes sense. I'll do that.

**Review by dimapihtar — COMMENTED** [review]
LGTM. I don't have any issues with ci tests for this PR.

**Comment by roclark** [comment]
Now including model evaluation on k8s as well.

**Comment by roclark** [comment]
Removed README in favor of the new documentation updates.

**Pull request merged**
